feat(useRcTableAdapter): remove all table imports, rewrite docs and c…
gazprom-neft/rc-table-adapter pull request #8
Opened 2021-12-22 10:59 UTC by N1MBER

feat(useRcTableAdapter): remove all table imports, rewrite docs and change example

2021-12-22 15:56 UTC, gizeasy requested changes
Идея с хуком хорошая, но по факту она не является хуком, это просто функция.
И кажется что ее можно декомпозировать:
1) cnTable, для составления стилей для таблицы
2) renderArrowIcon, рендер функция иконки

2021-12-28 08:45 UTC, gizeasy requested changes

2021-12-28 08:45 UTC, gizeasy commented on src/customPrefixCls/customPrefixCls.ts
> +import '@/useRcTableAdapter/UseRcTableAdapter.css'
лучше держдать css в одной папке с классогененротором

2021-12-28 08:45 UTC, gizeasy commented on src/customPrefixCls/customPrefixCls.ts
> +import '@/useRcTableAdapter/UseRcTableAdapter.css'
1) у нас блок называется rc-table, его бы переименовать в RcTable, чтоб как везде, камелкейсом
2) папку назвать RcTable чтоб  совподало с названием блока
3) экспортить типизированную функцию cnRcTable вместо customPrefixCls
4) забыл сделать экспорт из функции из папки напрямую
5) создай плиз сторю как использовать эту функцию

2021-12-28 08:45 UTC, gizeasy commented on src/CustomExpanIcon/CustomExpandIcon.tsx
> +import '@/useRcTableAdapter/UseRcTableAdapter.css'
Давай и часть стилей отвечающих за иконку вынесем в папку с компонентом иконки

2021-12-28 08:45 UTC, gizeasy commented on src/CustomExpanIcon/CustomExpandIcon.tsx
> +import '@/useRcTableAdapter/UseRcTableAdapter.css'
- забыл отдельно ее экспортить
- создай сторю с примером использования
- может переименуем ее в ExpandIcon?

2021-12-28 08:45 UTC, gizeasy commented on src/customPrefixCls/customPrefixCls.ts
> +import '@/useRcTableAdapter/UseRcTableAdapter.css'
![image](https://user-images.githubusercontent.com/13190808/147546869-daa44ffd-4d53-487f-b9b6-9a175a544d1d.png)

в темной теме текст не перекрашивается

2021-12-28 08:45 UTC, gizeasy commented on src/customPrefixCls/customPrefixCls.ts
> +import '@/useRcTableAdapter/UseRcTableAdapter.css'
сделай пример на русском
![image](https://user-images.githubusercontent.com/13190808/147547014-f3826169-0ebd-46dc-bc7a-f5a346044951.png)

2021-12-28 08:45 UTC, gizeasy commented on src/index.ts
> +export * from './useRcTableAdapter/useRcTableAdapter'
адаптер не является хуком
давай переименуем в rcTableAdapter

2021-12-28 12:58 UTC, arhayka commented on src/customPrefixCls/customPrefixCls.ts
> +import '@/useRcTableAdapter/UseRcTableAdapter.css'
все примеры можете мне оставить) я переделаю на русский

2021-12-28 13:18 UTC, gizeasy requested changes

2021-12-28 13:18 UTC, gizeasy commented on src/RcTable/RcTable.ts
> +export const cnRcTable: CnRcTable = props => {
сделай апишку такого типа 
```
cnRcTable(
    {
      size,
      zebraStriped,
      borderBetweenColumns,
      borderBetweenRows,
      verticalAlign,
      headerVerticalAlign,
    },
    [prefixCls]
  )
```

2021-12-28 13:43 UTC, gizeasy approved these changes

2021-12-28 13:43 UTC, merged